title: Alaina Holland
logo: "/images/logo.png?raw=true"
description: > 
  Hi! I'm Alaina Holland, a data enthusiast with an MBA and a master's in Data Science from Willamette University. With a background in the art world and experience in supply chain management, I specialize in turning complex data into actionable insights to solve business problems. Whether it's optimizing inventory systems, evaluating AI in telehealth, or even determining what it takes to survive 'The Bachelor', I'm passionate about making data work for you.

  **Find me on LinkedIn:** [LinkedIn/alainaholland](https://www.linkedin.com/in/alainaholland/)

  **Contact Information:**
  - **Phone**: (208) 860-7452
  - **Email**: [alainaholland27@gmail.com](mailto:alainaholland27@gmail.com)
  - **Website**: [www.alainaholland.com](http://www.alainaholland.com)

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
google_analytics: UA-000000-0 # Replace with your Google Analytics tracking ID
