title: Alaina Holland # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Welcome to my portfolio! I'm Alaina Holland, a Data Analyst who thrives on turning complex data into clear, actionable insights. With an MBA and a master's in Data Science from Willamette University, I specialize in optimizing business processes, creating interactive dashboards, and leveraging data to drive smart decisions.
  <br><br>
  Whether it's refining inventory systems, evaluating AI in telehealth, or dissecting what it takes to survive 'The Bachelor,' my passion lies in making data work for you.
  <br><br>
  <a href="https://www.linkedin.com/in/alainaholland/">View My LinkedIn Profile</a>
  <br><br>
  <a href="https://medium.com/@aholland_36794/">Check Me Out on Medium</a>
  <br><br>
  Or send me an email: <a href="mailto:alainaholland27@gmail.com">alainaholland27@gmail.com</a>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
