title: Alaina Holland
logo: "/images/logo.png?raw=true"
description: > 
  I like data and solving problems. With an MBA and a master's in Data Science from Willamette University, I enjoy turning complex data into actionable insights. Whether it's optimizing inventory systems, evaluating AI in telehealth, or figuring out what it takes to survive 'The Bachelor', I'm passionate about making data work for you.

  **Find me on LinkedIn:** [LinkedIn/alainaholland](https://www.linkedin.com/in/alainaholland/)

  **Contact Information:**
  - **Phone**: (208) 860-7452
  - **Email**: [alainaholland27@gmail.com](mailto:alainaholland27@gmail.com)
  - **Website**: [www.alainaholland.com](http://www.alainaholland.com)

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
google_analytics: UA-000000-0 # Replace with your Google Analytics tracking ID
